name: Release_Tags
on:
    push:
      tags:
        - "v*"  #on every tag created
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls
      - run: tail index.js


