name: Release_Tags
on:
  push:
    tags:
      - "*"

env:
  service_name: expense-backend


jobs:
  CI_Steps:
    uses: jyothsna-shrey/github-actions/.github/workflows/Release_Tags.yml@main
    secrets: inherit
    with:
      service_name: expense-backend